services:
  nginx:
    build:
      context: ./requirements/nginx/. # Path to the directory containing the Dockerfile
    image: # Name and tag for the built image
    ports:
      - "443:443" # Map port 8080 on the host to port 8080 in the container
    extra_hosts:
      - "tbenz.42.fr:127.0.0.1" # Add extra host entries to /etc/hosts in the container
